INSERT INTO country (name) VALUE ('BELARUS');
INSERT INTO country (name) VALUE ('RUSSIA');
INSERT INTO country (name) VALUE ('UKRAINE');
INSERT INTO country (name) VALUE ('GERMANY');
INSERT INTO country (name) VALUE ('CYPRUS');
INSERT INTO country (name) VALUE ('IZRAEL');
INSERT INTO country (name) VALUE ('INDIA');
INSERT INTO country (name) VALUE ('USA');
INSERT INTO country (name) VALUE ('AUSTRALIA');
INSERT INTO city (name, Country_id) VALUE ('MINSK', 1);
INSERT INTO city (name, Country_id) VALUE ('MOSCOW', 2);
INSERT INTO city (name, Country_id) VALUE ('ST.PETERSBURG', 2);
INSERT INTO city (name, Country_id) VALUE ('KIEV', 3);
INSERT INTO city (name, Country_id) VALUE ('FRANKFURT AM MAIN', 4);
INSERT INTO city (name, Country_id) VALUE ('NICOSIA', 5);
INSERT INTO city (name, Country_id) VALUE ('TEL-AVIV', 6);
INSERT INTO city (name, Country_id) VALUE ('NEW DELHI', 7);
INSERT INTO city (name, Country_id) VALUE ('LAS VEGAS', 8);
INSERT INTO city (name, Country_id) VALUE ('SAN FRACISKO', 8);
INSERT INTO city (name, Country_id) VALUE ('SYDNEY', 9);
INSERT INTO employee(name, last_name, phone) VALUES('Arkadii','Dobkin',null);
INSERT INTO employee(name, last_name, phone) VALUES('Iryna','Khvalko',null);
INSERT INTO employee(name, last_name, phone) VALUES('Alex','Kazlouski',null);
INSERT INTO employee(name, last_name, phone) VALUES('Oleg','Veramei',null);
INSERT INTO employee(name, last_name, phone) VALUES('Grigory','Perepechko',null);
INSERT INTO employee(name, last_name, phone) VALUES('Alexander','Kurilo',null);
INSERT INTO employee(name, last_name, phone) VALUES('Andrei','Navoichyk',null);
INSERT INTO employee(name, last_name, phone) VALUES('Yuliya','Khomich',null);
INSERT INTO employee(name, last_name, phone) VALUES('Anton','Novikau',null);
INSERT INTO employee(name, last_name, phone) VALUES('Alesia','Semenenko',null);
INSERT INTO employee(name, last_name, phone) VALUES('Galina','Tokareva',null);
INSERT INTO employee(name, last_name, phone) VALUES('Veronika','Lepekha',null);
INSERT INTO employee(name, last_name, phone) VALUES('Antonina','Rovda',null);
INSERT INTO employee(name, last_name, phone) VALUES('Pavel','Pliatniou',null);
INSERT INTO employee(name, last_name, phone) VALUES('Dzhamel','Agaua',null);
INSERT INTO employee(name, last_name, phone) VALUES('Victor','Kislyi',null);
INSERT INTO employee(name, last_name, phone) VALUES('Anastasiya','Siamionava',null);  
INSERT INTO employee(name, last_name, phone) VALUES('Ivan','Kavalchuk',null);
INSERT INTO economists(analize_type, Employee_id) VALUES('Revenue per employee', 2);
INSERT INTO economists(analize_type, Employee_id) VALUES('Total cost of ownership', 8);
INSERT INTO economists(analize_type, Employee_id) VALUES('Financial analysis', 11);
INSERT INTO economists(analize_type, Employee_id) VALUES('Financial analysis', 13);
INSERT INTO developers(project, Employee_id) VALUES('Vibers new', 4);
INSERT INTO developers(project, Employee_id) VALUES('World of Tanks new', 9);
INSERT INTO developers(project, Employee_id) VALUES('New casinos game', 12);
INSERT INTO developers(project, Employee_id) VALUES('New casinos game', 6);
INSERT INTO developers(project, Employee_id) VALUES('Schatz', 7);
INSERT INTO developers(project, Employee_id) VALUES('Schatz', 12);
INSERT INTO developers(project, Employee_id) VALUES('Schatz', 4);
INSERT INTO developers(project, Employee_id) VALUES('Schatz', 9);
INSERT INTO developers(project, Employee_id) VALUES('Schatz', 14);
INSERT INTO sales(client_count, Employee_id) VALUES(4, 5);
INSERT INTO sales(client_count, Employee_id) VALUES(3, 17);
INSERT INTO sales(client_count, Employee_id) VALUES(6, 10);
INSERT INTO sales(client_count, Employee_id) VALUES(5, 18);
INSERT INTO owner(Employee_id) VALUE(1);
INSERT INTO owner(Employee_id) VALUE(3);
INSERT INTO owner(Employee_id) VALUE(15);
INSERT INTO owner(Employee_id) VALUE(16);
INSERT INTO itcompany(reg_number, year,name) VALUES('191764022', '2010','Playtika');
INSERT INTO itcompany(reg_number, year,name) VALUES('190664298', '1998','Wargaming.net');
INSERT INTO itcompany(reg_number, year,name) VALUES('191699514', '2010','Viber');
INSERT INTO itcompany(reg_number, year,name) VALUES('101546673', '1993','Epam Systems');
INSERT INTO address(street, house,City_id) VALUES('Akademika Kuprevicha','1-1-110',1);
INSERT INTO address(street, house,City_id) VALUES('Partyzanski','178/2-38',1);
INSERT INTO address(street, house,City_id) VALUES('Platonova','20B',1);
INSERT INTO address(street, house,City_id) VALUES('9-ya Radialnaya','2',2);
INSERT INTO address(street, house,City_id) VALUES('Voronezhsaya','5',3);
INSERT INTO address(street, house,City_id) VALUES('Obuhovsckoi oborony','70-3A-41H',3);
INSERT INTO address(street, house,City_id) VALUES('Agion Omologion Avenue','105-23885',6);
INSERT INTO address(street, house,City_id) VALUES('Brullova','7',4);
INSERT INTO address(street, house,City_id) VALUES('Mainzer Landstrasse','49/49A-D60329',5);
INSERT INTO address(street, house,City_id) VALUES('Makedonitissas Street','46/CY-2417',7);
INSERT INTO address(street, house,City_id) VALUES('Viguan Nagar Street','402C',8);
INSERT INTO address(street, house,City_id) VALUES('Sahara Avenue','308W',9);
INSERT INTO address(street, house,City_id) VALUES('Dogpatch Street','2378CA',10);
INSERT INTO address(street, house,City_id) VALUES('Miller Street','116K',11);
INSERT INTO address(street, house,City_id) VALUES('George Street','269J',11);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 1,4);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 2,2);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 3,1);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 3,3);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 4,4);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 5,4);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 6,2);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 7,2);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 8,1);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 9,4);
INSERT INTO office(phone, adress_id,ITcompany_id) VALUES(null, 10,3);
INSERT INTO customer(name, Address_id) VALUES('NarayenComp', 11);
INSERT INTO customer(name, Address_id) VALUES('LasCasinoVegas', 12);
INSERT INTO customer(name, Address_id) VALUES('Hamquist', 13);
INSERT INTO customer(name, Address_id) VALUES('Renaistance', 14);
INSERT INTO customer(name, Address_id) VALUES('Yuncken', 15);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(1, 2);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(2, 1);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(3, 5);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(4, 3);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(4, 4);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(4, 1);
INSERT INTO itcompany_has_customer(ITcompany_id,Customer_id) VALUES(2, 5);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 3, 12967.57);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 2, 1115.17);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 12, 1984.28);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 6, 2471.43);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 17, 1215.65);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(1, 10, 750.84);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 16,22754.90);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 8,1023.54);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 11,1450.54);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 9,2100.00);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 5, 1008.52);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(2, 18,1202.10);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(3, 15,15000.27);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(3, 13,954.15);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(3, 2,1005.77);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(3, 4,2000.03);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,1,37520.51);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,2,1420.12);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,8,1200.86);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,11,1504.21);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,7,2004.17);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,12,750.26);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,4,960.52);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,9,1450.24);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,14,2630.25);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,17,1000.00);
INSERT INTO itcompany_has_employee(ITcompany_id,Employee_id,salary) VALUES(4,18,1003.54);